spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: pf1646
    password: fiap23
  jpa:
    hibernate:
      ddl-auto: none
      open-in-view: false
      show-sql: false